import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="p-5 text-black bg-white">
          <Link href={"/"} className="mr-2.5 ">
            홈
          </Link>
          <Link href={"/list"}>리스트</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
